/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ubuntuBold = localFont({
  src: "./fonts/Ubuntu-Bold.ttf",
  variable: "--font-ubuntu-bold",
  weight: "700",
});

const ubuntuLight = localFont({
  src: "./fonts/Ubuntu-Light.ttf",
  variable: "--font-ubuntu-light",
  weight: "300",
});

const ubuntuMedium = localFont({
  src: "./fonts/Ubuntu-Medium.ttf",
  variable: "--font-ubuntu-medium",
  weight: "500",
});

const ubuntuRegular = localFont({
  src: "./fonts/Ubuntu-Regular.ttf",
  variable: "--font-ubuntu-regular",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuLight.className} ${ubuntuMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
